/*
 * SwaggerHub resolve export yaml api
 *
 * Description about the API  email: 'Test@test.com'  
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BlockWithAllofAndProperties : TestBlock, IEquatable<BlockWithAllofAndProperties>
    { 
        /// <summary>
        /// Gets or Sets Attribute2
        /// </summary>

        [DataMember(Name="attribute2")]
        public string Attribute2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BlockWithAllofAndProperties {\n");
            sb.Append("  Attribute2: ").Append(Attribute2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BlockWithAllofAndProperties)obj);
        }

        /// <summary>
        /// Returns true if BlockWithAllofAndProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of BlockWithAllofAndProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BlockWithAllofAndProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Attribute2 == other.Attribute2 ||
                    Attribute2 != null &&
                    Attribute2.Equals(other.Attribute2)
                ) && base.Equals(other);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Attribute2 != null)
                    hashCode = hashCode * 59 + Attribute2.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BlockWithAllofAndProperties left, BlockWithAllofAndProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BlockWithAllofAndProperties left, BlockWithAllofAndProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
