/*
 * SwaggerHub resolve export yaml api
 *
 * Description about the API  email: 'Test@test.com'  
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ResponseBlock : IEquatable<ResponseBlock>
    { 
        /// <summary>
        /// List of things
        /// </summary>
        /// <value>List of things</value>

        [DataMember(Name="arrayAttributeName")]
        public List<AllOfresponseBlockArrayAttributeNameItems> ArrayAttributeName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseBlock {\n");
            sb.Append("  ArrayAttributeName: ").Append(ArrayAttributeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ResponseBlock)obj);
        }

        /// <summary>
        /// Returns true if ResponseBlock instances are equal
        /// </summary>
        /// <param name="other">Instance of ResponseBlock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseBlock other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ArrayAttributeName == other.ArrayAttributeName ||
                    ArrayAttributeName != null &&
                    ArrayAttributeName.SequenceEqual(other.ArrayAttributeName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ArrayAttributeName != null)
                    hashCode = hashCode * 59 + ArrayAttributeName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ResponseBlock left, ResponseBlock right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ResponseBlock left, ResponseBlock right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
