/*
 * SwaggerHub resolve export yaml api
 *
 * Description about the API  email: 'Test@test.com'  
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TestBlock : IEquatable<TestBlock>
    { 
        /// <summary>
        /// Example description with number datatype
        /// </summary>
        /// <value>Example description with number datatype</value>

        [DataMember(Name="attribute1")]
        public decimal? Attribute1 { get; set; }

        /// <summary>
        /// datetime example
        /// </summary>
        /// <value>datetime example</value>

        [DataMember(Name="dateTimeAttributeTimestamp")]
        public DateTime? DateTimeAttributeTimestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestBlock {\n");
            sb.Append("  Attribute1: ").Append(Attribute1).Append("\n");
            sb.Append("  DateTimeAttributeTimestamp: ").Append(DateTimeAttributeTimestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TestBlock)obj);
        }

        /// <summary>
        /// Returns true if TestBlock instances are equal
        /// </summary>
        /// <param name="other">Instance of TestBlock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestBlock other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Attribute1 == other.Attribute1 ||
                    Attribute1 != null &&
                    Attribute1.Equals(other.Attribute1)
                ) && 
                (
                    DateTimeAttributeTimestamp == other.DateTimeAttributeTimestamp ||
                    DateTimeAttributeTimestamp != null &&
                    DateTimeAttributeTimestamp.Equals(other.DateTimeAttributeTimestamp)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Attribute1 != null)
                    hashCode = hashCode * 59 + Attribute1.GetHashCode();
                    if (DateTimeAttributeTimestamp != null)
                    hashCode = hashCode * 59 + DateTimeAttributeTimestamp.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TestBlock left, TestBlock right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TestBlock left, TestBlock right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
