/*
 * SwaggerHub resolve export yaml api
 *
 * Description about the API  email: 'Test@test.com'  
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Summary of the endpoint
        /// </summary>
        /// <remarks>description of the endpoint</remarks>
        /// <param name="body"></param>
        /// <response code="202">Response description.</response>
        [HttpPost]
        [Route("/test")]
        [ValidateModelState]
        [SwaggerOperation("TestPost")]
        [SwaggerResponse(statusCode: 202, type: typeof(ResponseBlock), description: "Response description.")]
        public virtual IActionResult TestPost([FromBody]TestCreateRequest body)
        { 
            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202, default(ResponseBlock));
            string exampleJson = null;
            exampleJson = "{\n  \"arrayAttributeName\" : [ \"\", \"\" ]\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ResponseBlock>(exampleJson)
                        : default(ResponseBlock);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
